<a href="https://colab.research.google.com/github/NilotpalMaitra/Pytorch/blob/main/Tensorsinpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

Tensor initialization

Directly from data

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

From a Numpy Array

In [4]:
np_array = np.array(data)
x_np=torch.from_numpy(np_array)

From another tensor:

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} /n")

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} /n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) /n
Random Tensor: 
 tensor([[0.7869, 0.1454],
        [0.7410, 0.1656]]) /n


With Random or constant values:

(shape is a tupe of tensor dimensioms. In the functions below, it determines the dimensionality of the output tensor)

In [6]:
shape = (2,3,)
rand_tensor=torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


print(f"Random Tensor: \n {rand_tensor} /n")
print(f"Ones Tensor: \n {ones_tensor} /n")
print(f"Zeros Tensor: \n {zeros_tensor} /n")

Random Tensor: 
 tensor([[0.8079, 0.3718, 0.3449],
        [0.7285, 0.5980, 0.5327]]) /n
Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) /n
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) /n


Tensor attributes: it describes their shape, datatype, and the device on which they are stored.

In [7]:
tensor = torch. rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Tensor Operations:
transposing, indexing slicing, mathematical operations, linear algebra, random sampling.

In [8]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Standard numpy -like indexing and slicing:

In [9]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining tensors

In [10]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Multiplying tensors

In [11]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n") #Computing element wise product
print(f"tensor * tensor \n {tensor * tensor}") #Other form of style

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Matrix Multiplication between two tensors

In [12]:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In place operations

In [13]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Tensor to Numpy array

In [14]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n:{n}")

t: tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


NumPy array to Tensor

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)